/** Amazon 一日运营工作流 Demo 数据 */

export const AMAZON_OPERATOR = { name: '刘洋', role: 'Amazon 运营' }

/** 工作流步骤定义 */
export const AMAZON_DAILY_STEPS = [
  { key: 'messages', label: '买家消息', tab: 'messages', hint: '先回消息，避免扣绩效' },
  { key: 'account', label: '账户状况', tab: 'account', hint: '爆红指标要马上处理' },
  { key: 'reviews', label: '差评预警', tab: 'reviews', hint: '1-3 星评价需跟进' },
  { key: 'coupons', label: '优惠券', tab: 'coupons', hint: '过期或异常要预警' },
  { key: 'news', label: '卖家新闻', tab: 'news', hint: '平台政策与通知' },
  { key: 'shipments', label: '货件到货', tab: 'shipments', hint: '缺件、无货要预警' },
  { key: 'cases', label: 'Case 回复', tab: 'cases', hint: '平台回复单独提醒' },
]

/** 统一回复模板 */
export const MESSAGE_REPLY_TEMPLATES = [
  {
    id: 'tpl_delay',
    title: '发货延迟致歉',
    body: '您好，非常抱歉您的订单发货有所延迟。我们已加急处理，预计 24 小时内发出，并会同步物流单号。感谢您的耐心与理解。',
  },
  {
    id: 'tpl_tracking',
    title: '物流查询回复',
    body: '您好，您的包裹已发出，物流单号：{trackingNo}。预计 {eta} 送达。如有异常请随时联系我们，我们会第一时间协助处理。',
  },
  {
    id: 'tpl_defect',
    title: '产品问题致歉',
    body: '您好，非常抱歉产品未能达到您的预期。我们重视每一位客户的体验，可为您安排补发或全额退款，请告知您的偏好，我们会立即处理。',
  },
  {
    id: 'tpl_thanks',
    title: '好评感谢',
    body: '您好，感谢您的好评与支持！您的认可是我们持续改进的动力。祝您使用愉快，期待再次为您服务。',
  },
]

export const ACCOUNT_METRIC_STATUS = {
  normal: { label: '正常', type: 'success' },
  warning: { label: '预警', type: 'warning' },
  critical: { label: '爆红', type: 'danger' },
}

export const COUPON_STATUS = {
  active: { label: '生效中', type: 'success' },
  expiring: { label: '即将过期', type: 'warning' },
  expired: { label: '已过期', type: 'info' },
  abnormal: { label: '异常', type: 'danger' },
}

export const SHIPMENT_STATUS = {
  in_transit: { label: '运输中', type: 'primary' },
  delivered: { label: '已送达', type: 'success' },
  shortage: { label: '缺件', type: 'danger' },
  closed_no_stock: { label: '完成无货', type: 'danger' },
}

// ── Seed data ──────────────────────────────────────────────

export const BUYER_MESSAGES_SEED = [
  {
    id: 'msg_1',
    storeId: 'demo_amazon_1',
    buyerName: 'John M.',
    orderNo: '114-2847561-9283746',
    subject: 'Where is my order?',
    preview: 'I ordered 3 days ago but still no tracking update...',
    receivedAt: '2026-06-25 07:42:00',
    slaHours: 24,
    status: 'pending',
    repliedAt: null,
    templateUsed: null,
  },
  {
    id: 'msg_2',
    storeId: 'demo_amazon_1',
    buyerName: 'Sarah K.',
    orderNo: '114-9182736-4528190',
    subject: 'Product defect',
    preview: 'The tent pole arrived bent and cannot be used...',
    receivedAt: '2026-06-25 09:15:00',
    slaHours: 24,
    status: 'pending',
    repliedAt: null,
    templateUsed: null,
  },
  {
    id: 'msg_3',
    storeId: 'demo_amazon_2',
    buyerName: 'Hans B.',
    orderNo: '171-3847562-9182736',
    subject: 'Rücksendung',
    preview: 'Ich möchte den Artikel zurückgeben...',
    receivedAt: '2026-06-25 06:30:00',
    slaHours: 24,
    status: 'replied',
    repliedAt: '2026-06-25 08:00:00',
    templateUsed: 'tpl_defect',
  },
]

export const ACCOUNT_METRICS_SEED = [
  {
    id: 'metric_1',
    storeId: 'demo_amazon_1',
    metricKey: 'odr',
    label: '订单缺陷率 ODR',
    value: '1.2%',
    threshold: '< 1%',
    status: 'critical',
    trend: 'up',
    reportedAt: '2026-06-25 08:00:00',
    note: '近 7 日有 3 笔差评关联订单，需优先处理买家消息与差评',
  },
  {
    id: 'metric_2',
    storeId: 'demo_amazon_1',
    metricKey: 'late_ship',
    label: '迟发率',
    value: '3.8%',
    threshold: '< 4%',
    status: 'warning',
    trend: 'up',
    reportedAt: '2026-06-25 08:00:00',
    note: 'MFN 订单有 2 单临近发货截止',
  },
  {
    id: 'metric_3',
    storeId: 'demo_amazon_1',
    metricKey: 'cancel',
    label: '取消率',
    value: '0.5%',
    threshold: '< 2.5%',
    status: 'normal',
    trend: 'stable',
    reportedAt: '2026-06-25 08:00:00',
    note: '',
  },
  {
    id: 'metric_4',
    storeId: 'demo_amazon_1',
    metricKey: 'health',
    label: '账户健康评级',
    value: 'At Risk',
    threshold: 'Good',
    status: 'critical',
    trend: 'down',
    reportedAt: '2026-06-25 08:00:00',
    note: 'ODR 超标是主因，今日务必处理差评与买家消息',
  },
  {
    id: 'metric_5',
    storeId: 'demo_amazon_2',
    metricKey: 'odr',
    label: '订单缺陷率 ODR',
    value: '0.6%',
    threshold: '< 1%',
    status: 'normal',
    trend: 'stable',
    reportedAt: '2026-06-25 08:00:00',
    note: '',
  },
  {
    id: 'metric_6',
    storeId: 'demo_amazon_2',
    metricKey: 'health',
    label: '账户健康评级',
    value: 'Good',
    threshold: 'Good',
    status: 'normal',
    trend: 'stable',
    reportedAt: '2026-06-25 08:00:00',
    note: '',
  },
]

export const REVIEWS_SEED = [
  {
    id: 'rev_1',
    storeId: 'demo_amazon_1',
    orderNo: '114-5628391-0173846',
    asin: 'B08XYZ1234',
    productName: '轻量双人徒步帐篷 3-4人',
    rating: 1,
    content: 'Pole broke on first use. Very disappointed.',
    reviewedAt: '2026-06-24 22:30:00',
    status: 'pending',
    handledAt: null,
  },
  {
    id: 'rev_2',
    storeId: 'demo_amazon_1',
    orderNo: '114-3300123-4455667',
    asin: 'B09ABC5678',
    productName: '碳纤维登山杖一对',
    rating: 2,
    content: 'One pole is shorter than the other.',
    reviewedAt: '2026-06-25 06:00:00',
    status: 'pending',
    handledAt: null,
  },
  {
    id: 'rev_3',
    storeId: 'demo_amazon_2',
    orderNo: '171-9988776-5544332',
    asin: 'B07DEF9012',
    productName: '折叠露营椅',
    rating: 3,
    content: 'Stuhl ist ok, aber Verpackung war beschädigt.',
    reviewedAt: '2026-06-24 18:00:00',
    status: 'pending',
    handledAt: null,
  },
]

export const COUPONS_SEED = [
  {
    id: 'cpn_1',
    storeId: 'demo_amazon_1',
    name: 'Prime Day 帐篷 15% OFF',
    discount: '15%',
    startAt: '2026-06-20',
    endAt: '2026-06-25',
    status: 'expiring',
    redemptions: 186,
    budget: 500,
    note: '今日 23:59 到期，注意是否续期',
  },
  {
    id: 'cpn_2',
    storeId: 'demo_amazon_1',
    name: '登山杖满减 $5',
    discount: '$5',
    startAt: '2026-06-01',
    endAt: '2026-06-18',
    status: 'expired',
    redemptions: 42,
    budget: 200,
    note: '已过期但前台仍可能展示，需检查',
  },
  {
    id: 'cpn_3',
    storeId: 'demo_amazon_1',
    name: '睡袋新品 10% OFF',
    discount: '10%',
    startAt: '2026-06-22',
    endAt: '2026-07-15',
    status: 'active',
    redemptions: 28,
    budget: 300,
    note: '',
  },
  {
    id: 'cpn_4',
    storeId: 'demo_amazon_2',
    name: 'EU Summer Sale',
    discount: '20%',
    startAt: '2026-06-15',
    endAt: '2026-06-10',
    status: 'abnormal',
    redemptions: 0,
    budget: 100,
    note: '结束日期早于开始日期，配置异常',
  },
]

export const SELLER_NEWS_SEED = [
  {
    id: 'news_1',
    storeId: 'demo_amazon_1',
    title: '美国站 FBA 入库限制调整',
    summaryPlain:
      '从下月起，部分大件类目 FBA 入库上限会收紧。你卖的帐篷和睡袋可能受影响，建议这周就把在途货件发完，别等月底。',
    category: 'FBA 政策',
    publishedAt: '2026-06-25 07:00:00',
    importance: 'high',
  },
  {
    id: 'news_2',
    storeId: 'demo_amazon_1',
    title: '买家消息回复时效计入绩效',
    summaryPlain:
      '24 小时内必须回复买家消息，超时会直接影响账户健康。今天先把未读消息清掉，用统一模板回复最快。',
    category: '绩效政策',
    publishedAt: '2026-06-25 06:30:00',
    importance: 'high',
  },
  {
    id: 'news_3',
    storeId: 'demo_amazon_2',
    title: '欧洲站 VAT 申报提醒',
    summaryPlain:
      'Q2 增值税申报截止日期临近。欧洲站卖家需在本月底前完成申报，逾期可能限制销售权限。',
    category: '合规',
    publishedAt: '2026-06-24 16:00:00',
    importance: 'normal',
  },
]

export const SHIPMENTS_SEED = [
  {
    id: 'shp_1',
    storeId: 'demo_amazon_1',
    shipmentId: 'FBA16XXXX1',
    sku: 'AMZ-001',
    productName: '轻量双人徒步帐篷 3-4人',
    unitsExpected: 500,
    unitsReceived: 500,
    status: 'delivered',
    eta: '2026-06-24',
    updatedAt: '2026-06-24 14:00:00',
    alertLevel: 'normal',
    note: '已全部上架',
  },
  {
    id: 'shp_2',
    storeId: 'demo_amazon_1',
    shipmentId: 'FBA16XXXX2',
    sku: 'AMZ-003',
    productName: '碳纤维登山杖一对',
    unitsExpected: 800,
    unitsReceived: 620,
    status: 'shortage',
    eta: '2026-06-25',
    updatedAt: '2026-06-25 09:00:00',
    alertLevel: 'danger',
    note: '短少 180 件，需开 Case 索赔',
  },
  {
    id: 'shp_3',
    storeId: 'demo_amazon_1',
    shipmentId: 'FBA16XXXX3',
    sku: 'AMZ-002',
    productName: '四季露营睡袋 -10℃',
    unitsExpected: 300,
    unitsReceived: 0,
    status: 'closed_no_stock',
    eta: '2026-06-23',
    updatedAt: '2026-06-24 10:00:00',
    alertLevel: 'danger',
    note: '货件显示已完成但 FBA 可售为 0，紧急核查',
  },
  {
    id: 'shp_4',
    storeId: 'demo_amazon_2',
    shipmentId: 'FBA16XXXX4',
    sku: 'AMZ-004',
    productName: '折叠露营椅',
    unitsExpected: 200,
    unitsReceived: 0,
    status: 'in_transit',
    eta: '2026-06-28',
    updatedAt: '2026-06-25 08:00:00',
    alertLevel: 'normal',
    note: '',
  },
]

export const CASES_SEED = [
  {
    id: 'case_1',
    storeId: 'demo_amazon_1',
    caseId: '12345678901',
    subject: 'FBA 货件短少索赔 - FBA16XXXX2',
    lastReplyFrom: 'amazon',
    lastReplyAt: '2026-06-25 08:30:00',
    status: 'pending_reply',
    preview: 'We need additional documentation regarding the shortage...',
    hasNewReply: true,
    read: false,
  },
  {
    id: 'case_2',
    storeId: 'demo_amazon_1',
    caseId: '12345678902',
    subject: 'Listing 图片违规申诉',
    lastReplyFrom: 'seller',
    lastReplyAt: '2026-06-24 16:00:00',
    status: 'open',
    preview: 'We have updated the main image to comply with guidelines.',
    hasNewReply: false,
    read: true,
  },
  {
    id: 'case_3',
    storeId: 'demo_amazon_2',
    caseId: '12345678903',
    subject: 'VAT 注册信息更新',
    lastReplyFrom: 'amazon',
    lastReplyAt: '2026-06-25 07:00:00',
    status: 'pending_reply',
    preview: 'Please provide updated VAT certificate by June 30...',
    hasNewReply: true,
    read: false,
  },
]
