/** 亿拓户外 — 全公司运营任务（与运营绑定串联） */
export const OPERATION_TASKS = [
  {
    id: 1,
    employeeId: 'demo_emp_1',
    title: 'Temu 爆款双人帐篷官方仓补货 1,800 件',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '王一鸣',
    category: '库存',
    priority: 'high',
    status: '进行中',
    progress: 65,
    due: '今天 18:00',
    updatedAt: '11:20',
  },
  {
    id: 2,
    employeeId: 'demo_emp_2',
    title: 'Temu 碳纤维登山杖紧急补货',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '李婷',
    category: '库存',
    priority: 'high',
    status: '进行中',
    progress: 40,
    due: '今天 18:00',
    updatedAt: '10:42',
  },
  {
    id: 3,
    employeeId: 'demo_emp_1',
    title: 'Temu 2 个亏损 SKU 调价评估',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '王一鸣',
    category: '定价',
    priority: 'high',
    status: '待处理',
    progress: 0,
    due: '今天 20:00',
    updatedAt: '09:48',
  },
  {
    id: 4,
    employeeId: 'demo_emp_3',
    title: '速卖通户外睡袋系列 86 SKU 刊登',
    platform: 'AliExpress',
    platformKey: 'aliexpress',
    assignee: '张强',
    category: '上架',
    priority: 'medium',
    status: '已完成',
    progress: 100,
    due: '今天 12:00',
    updatedAt: '09:20',
  },
  {
    id: 5,
    employeeId: 'demo_emp_1',
    title: 'Temu 45 日滞销冲锋衣清仓方案',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '王一鸣',
    category: '库存',
    priority: 'medium',
    status: '待处理',
    progress: 0,
    due: '明天',
    updatedAt: '09:15',
  },
  {
    id: 6,
    employeeId: 'demo_emp_1',
    title: '竞店松本户外新品对比报告',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '王一鸣',
    category: '运营',
    priority: 'medium',
    status: '待处理',
    progress: 0,
    due: '明天',
    updatedAt: '10:15',
  },
  {
    id: 7,
    employeeId: 'demo_emp_2',
    title: '官方仓太阳能马灯补货发货',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '李婷',
    category: '库存',
    priority: 'high',
    status: '进行中',
    progress: 25,
    due: '今天 21:00',
    updatedAt: '08:30',
  },
  {
    id: 8,
    employeeId: 'demo_emp_1',
    title: 'Temu 爆款碳纤维登山杖全公司通报',
    platform: 'Temu',
    platformKey: 'temu',
    assignee: '王一鸣',
    category: '运营',
    priority: 'medium',
    status: '已完成',
    progress: 100,
    due: '今天 10:00',
    updatedAt: '09:15',
  },
  {
    id: 9,
    employeeId: 'demo_emp_3',
    title: '速卖通 JIT 未发货订单跟进',
    platform: 'AliExpress',
    platformKey: 'aliexpress',
    assignee: '张强',
    category: '订单',
    priority: 'high',
    status: '进行中',
    progress: 30,
    due: '今天 17:00',
    updatedAt: '11:05',
  },
  {
    id: 10,
    employeeId: 'demo_emp_4',
    title: '独立站待发货订单处理',
    platform: '独立站',
    platformKey: 'dtc',
    assignee: '陈敏',
    category: '订单',
    priority: 'high',
    status: '待处理',
    progress: 0,
    due: '今天 18:00',
    updatedAt: '10:50',
  },
  {
    id: 11,
    employeeId: 'demo_emp_5',
    title: '1688 双人帐篷采购单付款跟进',
    platform: '1688',
    platformKey: '1688',
    assignee: '赵磊',
    category: '采购',
    priority: 'high',
    status: '进行中',
    progress: 50,
    due: '今天 17:30',
    updatedAt: '11:10',
  },
]

export const PLATFORM_OPS_STATUS = [
  { platform: 'Temu', owner: '王一鸣', health: 84, activeTasks: 5, overdueTasks: 0, todayDone: 1, alertLevel: 'warning', summary: '补货、亏损调价、滞销清仓进行中' },
  { platform: 'AliExpress', owner: '张强', health: 88, activeTasks: 0, overdueTasks: 0, todayDone: 1, alertLevel: 'normal', summary: '户外睡袋刊登已完成' },
  { platform: '仓储', owner: '李婷', health: 90, activeTasks: 2, overdueTasks: 0, todayDone: 0, alertLevel: 'warning', summary: '帐篷、登山杖补货发货中' },
]

export const TASK_STATUS_OPTIONS = ['全部', '待处理', '进行中', '已完成', '已逾期']

export const TASK_STATUS_META = {
  待处理: { type: 'info', label: '待处理' },
  进行中: { type: 'primary', label: '进行中' },
  已完成: { type: 'success', label: '已完成' },
  已逾期: { type: 'danger', label: '已逾期' },
}
