/** 运营问题处理反馈 Demo 种子（老板端首次可见） */

export const OPS_FEEDBACK_SEED = [
  {
    id: 'fb_seed_1',
    taskId: 'issue_temu_restock_demo_temu_1_SKU001',
    employeeId: 'demo_emp_1',
    employeeName: '王一鸣',
    employeeRole: 'Temu 运营',
    platform: 'Temu',
    platformKey: 'temu',
    taskTitle: '补货跟进：轻量双人徒步帐篷',
    category: '库存',
    outcome: 'resolved',
    outcomeLabel: '已处理',
    feedback: '已联系仓库安排 1,800 件发往官方仓，预计明日到仓。爆款通报已同步全公司。',
    storeName: '亿拓 Temu 美国店',
    date: '',
    submittedAt: '2026-06-25 17:20:00',
  },
  {
    id: 'fb_seed_2',
    taskId: 'issue_ae_jit_demo_aliexpress_1_WM10092837461',
    employeeId: 'demo_emp_3',
    employeeName: '张强',
    employeeRole: 'AliExpress 运营',
    platform: 'AliExpress',
    platformKey: 'aliexpress',
    taskTitle: 'JIT 未发货：AE20260625001',
    category: '订单',
    outcome: 'in_progress',
    outcomeLabel: '跟进中',
    feedback: '已与物流确认揽收时间，2 单今日 17:00 前出库；另 1 单缺货正在调拨。',
    storeName: '亿拓速卖通旗舰店',
    date: '',
    submittedAt: '2026-06-25 16:45:00',
  },
  {
    id: 'fb_seed_3',
    taskId: 'issue_amz_msg_demo_amazon_1_1',
    employeeId: 'demo_emp_6',
    employeeName: '刘洋',
    employeeRole: 'Amazon 运营',
    platform: 'Amazon',
    platformKey: 'amazon',
    taskTitle: '买家消息待回复：Shipping delay inquiry',
    category: '客服',
    outcome: 'resolved',
    outcomeLabel: '已处理',
    feedback: '已用模板回复并附物流单号，买家确认收到。ODR 暂无影响。',
    storeName: '亿拓 Amazon 美国站',
    date: '',
    submittedAt: '2026-06-25 15:30:00',
  },
  {
    id: 'fb_seed_4',
    taskId: 'issue_1688_pay_demo_1688_1_PO001',
    employeeId: 'demo_emp_5',
    employeeName: '赵磊',
    employeeRole: '1688 采购',
    platform: '1688',
    platformKey: '1688',
    taskTitle: '采购单待付款：PO20260624001',
    category: '采购',
    outcome: 'resolved',
    outcomeLabel: '已处理',
    feedback: '财务已审批，双人帐篷采购单 ¥28,600 已付款，供应商确认 3 日内发货。',
    storeName: '亿拓 1688 主采购号',
    date: '',
    submittedAt: '2026-06-25 14:10:00',
  },
  {
    id: 'fb_seed_5',
    taskId: 'issue_wm_listing_demo_walmart_1_wm_issue_1',
    employeeId: 'demo_emp_7',
    employeeName: '周婷',
    employeeRole: 'Walmart 运营',
    platform: 'Walmart',
    platformKey: 'walmart',
    taskTitle: 'Listing 问题：未发布',
    category: 'Listing',
    outcome: 'need_help',
    outcomeLabel: '需协助',
    feedback: '主图已重制为 2000×2000，但后台仍提示分辨率不足，怀疑是缓存问题，请管理员协助联系 Walmart 支持。',
    storeName: '亿拓 Walmart 美国店',
    date: '',
    submittedAt: '2026-06-25 11:50:00',
  },
  {
    id: 'fb_seed_assign_1',
    taskId: 'assign_seed_1',
    employeeId: 'demo_emp_1',
    employeeName: '王一鸣',
    employeeRole: 'Temu 运营',
    platform: 'Temu',
    platformKey: 'temu',
    taskTitle: '整理 Temu 爆款通报材料并同步仓储',
    category: '运营',
    outcome: 'in_progress',
    outcomeLabel: '跟进中',
    feedback: '通报 PPT 初稿已完成 60%，已与仓储确认碳纤维登山杖补货节奏，预计今日 20:00 前提交终稿。',
    storeName: '—',
    date: '',
    submittedAt: '2026-06-25 15:10:00',
  },
]

export const OUTCOME_OPTIONS = [
  { value: 'resolved', label: '已处理', type: 'success' },
  { value: 'in_progress', label: '跟进中', type: 'primary' },
  { value: 'need_help', label: '需协助', type: 'warning' },
  { value: 'blocked', label: '受阻', type: 'danger' },
]

export const OUTCOME_MAP = Object.fromEntries(OUTCOME_OPTIONS.map((o) => [o.value, o]))
